name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  test:
    name: Tests Action
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'
    - name: Run Tests
      run: go test